# Lesson 6:  Scikit-Learn Preprocessing and  TensorFlow Basics

In [1]:
pip install tensorflow

You should consider upgrading via the '/Users/jeffreycostales/opt/anaconda3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data=np.random.randint(0,100,(10,2))

In [5]:
data

array([[58, 81],
       [43, 10],
       [83, 64],
       [ 5, 80],
       [25,  1],
       [42, 63],
       [50, 60],
       [33,  1],
       [ 1, 72],
       [ 3, 83]])

In [6]:
scaler_model=MinMaxScaler()

In [7]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [8]:
scaler_model.fit(data)

MinMaxScaler()

In [9]:
scaler_model.transform(data)

array([[0.69512195, 0.97560976],
       [0.51219512, 0.1097561 ],
       [1.        , 0.76829268],
       [0.04878049, 0.96341463],
       [0.29268293, 0.        ],
       [0.5       , 0.75609756],
       [0.59756098, 0.7195122 ],
       [0.3902439 , 0.        ],
       [0.        , 0.86585366],
       [0.02439024, 1.        ]])

In [10]:
scaler_model.fit_transform(data)

array([[0.69512195, 0.97560976],
       [0.51219512, 0.1097561 ],
       [1.        , 0.76829268],
       [0.04878049, 0.96341463],
       [0.29268293, 0.        ],
       [0.5       , 0.75609756],
       [0.59756098, 0.7195122 ],
       [0.3902439 , 0.        ],
       [0.        , 0.86585366],
       [0.02439024, 1.        ]])

In [11]:
import pandas as pd

In [12]:
mydata = np.random.randint(0,101,(50,4))

In [13]:
mydata

array([[  6,  18,  28,  62],
       [ 98,  58,  76,  22],
       [ 59,  35,  43,  59],
       [ 54,  48,  56,  38],
       [ 43,  77,  23,  54],
       [  4,  98,  14,  19],
       [ 63,  84,  13,  22],
       [ 52,  85,  41,  48],
       [ 71,  43,  48,  86],
       [ 61,  66,  22,   6],
       [ 15,  89, 100,  82],
       [ 59,  87,  45,  58],
       [ 81,   6,  41,  56],
       [ 97,  53,  27,  83],
       [ 68,  40,  71,  94],
       [ 54,  58,  32,  20],
       [ 10,   3,  49,  14],
       [ 73,  97,  20,   1],
       [ 65,  50,  69,  43],
       [ 93,  77,  34,  47],
       [ 43,  43,  46,   7],
       [ 36,  38,  44,  26],
       [ 74,  49,  10,  42],
       [ 25,  19,   3,  81],
       [ 75,  24,  16,  36],
       [ 93,  21,  36,  55],
       [ 80,  22,  93,  63],
       [ 63,  84,  37,  34],
       [ 59,   0,  15,  70],
       [ 47,  95,  95,  26],
       [ 82,  37,  18,  14],
       [ 74,  87,  87,  99],
       [ 80,  90,  82,  21],
       [ 41,   7,   2,  26],
       [ 78,  

In [14]:
df = pd.DataFrame(data=mydata,columns=['f1','f2','f3','label'])

In [15]:
df

f1  f2   f3  label
0    6  18   28     62
1   98  58   76     22
2   59  35   43     59
3   54  48   56     38
4   43  77   23     54
5    4  98   14     19
6   63  84   13     22
7   52  85   41     48
8   71  43   48     86
9   61  66   22      6
10  15  89  100     82
11  59  87   45     58
12  81   6   41     56
13  97  53   27     83
14  68  40   71     94
15  54  58   32     20
16  10   3   49     14
17  73  97   20      1
18  65  50   69     43
19  93  77   34     47
20  43  43   46      7
21  36  38   44     26
22  74  49   10     42
23  25  19    3     81
24  75  24   16     36
25  93  21   36     55
26  80  22   93     63
27  63  84   37     34
28  59   0   15     70
29  47  95   95     26
30  82  37   18     14
31  74  87   87     99
32  80  90   82     21
33  41   7    2     26
34  78  58   80     56
35  13  58   13     51
36  99  52    4     88
37  54  43   78     27
38  22  25   39     50
39  16  28   84     88
40  48  58   29      9
41  19  86   16     38
42  28  58   19     16
43   1  43   17      3
44  59  38   41     69
45  56  16   35     37
46  99  80   16     45
47  38  76   27     37
48  45  83    0     64
49  91  65  100     82

In [16]:
X=df[['f1','f2','f3']]

In [17]:
y=df['label']

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>